apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-yjpg
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0031-tenant/tkrw-pr712-0075-0031-app/devfile-sample-yjpg@sha256:931a39d18dac51270ada63edbee1bc4bf6ac2b65c9d2b7a81b73e5b71606aaec
        name: my-nodejs
        resources: {}
status: {}
